### ISSUE TITLE
Document how to run your own harbor proxy

### ISSUE THREAD

**Issue by castrojo** [ublue-os/website#344]
For local dev and for people with multiple machines ... it'd be nice to be able to just run a proxy to cache stuff, ala apt-cache-ng back in the day!

https://tanzu.vmware.com/developer/guides/harbor-as-docker-proxy/

**Comment by castrojo** [comment]
Ok I got this from @p5 and I'm able to successfully cache pulls and other OCI artifacts, but it errors out on the signed images. 

I'm pretty sure it's a configuration issue but I haven't had time to investigate, tossing my config in here. 

```
jorge@trunks ~/registry % cat docker-compose.yml 
version: '3'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_LOG_LEVEL: "info"
      REGISTRY_PROXY_REMOTEURL: https://ghcr.io
```
